### PR TITLE
fix #19

### LINKED ISSUE #19: Markdown issues in 1.4.0 release
I noticed this difference in the upgrade from 1.3.10 to 1.4.0

1.4.0 outputs this:

```markdown
* [[e09e75b338](https://github.com/organization/private-repo/commit/e09e75b338) - subsystem: summary (James Young) #220
```
* [[e09e75b338](https://github.com/organization/private-repo/commit/e09e75b338) - subsystem: summary (James Young) #220

1.3.10 would output this:

```markdown
* [[`361ac84d97`](https://github.com/organization/private-repo/commit/361ac84d97)] - **subsystem**: summary (James Young) [#214](https://github.com/organization/private-repo/pull/214)
```
* [[`361ac84d97`](https://github.com/organization/private-repo/commit/361ac84d97)] - **subsystem**: summary (James Young) [#214](https://github.com/organization/private-repo/pull/214)

I haven't had a chance to look at the changes yet, but wanted to go ahead and log the issue.

### PR DESCRIPTION
**Pull request by maboiteaspam**
Restore original  Markdown formatting.

### CODE REVIEW

**Comment by maboiteaspam** [comment]
I m not really sure if i should go further in the release process ? And in that eventuality, how to proceed.

Anyway, they look really cool now 

* [[`23efb05cc3`](https://github.com/nodejs/io.js/commit/23efb05cc3)] - **doc**: document fs.watchFile behaviour on ENOENT (Brendan Ashworth) [#2093](https://github.com/nodejs/io.js/pull/2093)
* [[`1afc0c9e86`](https://github.com/nodejs/io.js/commit/1afc0c9e86)] - **fs**: fix error on bad listener type (Brendan Ashworth) [#2093](https://github.com/nodejs/io.js/pull/2093)

Too bad I dropped that error into the source.

**Comment by rvagg** [comment]
lgtm, just stop short of bumping version and publishing, I'll hang on to that responsibility for now

**Comment by maboiteaspam** [comment]
sure. 

I m buggy about the last comment made by some guys on iojs project, about the missing commits.

Should i just checkout io project and run the command then check the commits listed to figure out ?

**Comment by rvagg** [comment]
Yeah, missing commits, ignore that for now, it's not relevant for this but it is an interesting problem that I'd love to find a solution to.

Basically if you have multiple branches and tag on them, like this:

```
branch1 ----- a ----- c -------------------------

branch2 --- b ------------- d -------------------
```

and you want to do a `changelog-maker` on branch1 from tag `c` to the current HEAD you will only get commits from the time of tag `d` onwards even though it's on a completely different branch. This is because we just look at the list of tags, regardless of which branch they are on and use the time of the latest tag as our starting point.

It's solvable now by using `changelog-maker --start-ref=c`, but as we do more multi-branch releases in io.js this is increasingly becoming a problem.

So we need a way to list tags on the current branch only, ignoring other branches.

**Comment by maboiteaspam** [comment]
OK, thanks a lot for explanations ! I ll try to figure out about it.

**Comment by rvagg** [comment]
happy for you to merge this btw then I can cut a new relesae

**Pull request merged**
